[Settings]
ImproveCivilianVariety=0
UseParentVoices=0

;Missions

[male01]
ROBAD1=male01,dnmolc2
MISSIONALL=male01
MISSIONGAMEPLAY=male01
MISSION_TORENO2=dnmolc2

[bfyri]
PLS=bfyri,slut
MISSIONALL=bfyri
MISSIONGAMEPLAY=bfyri
MISSION_HOODS5=slut

[bmost]
FLINTC=bmost,mrwht
MISSIONALL=bmost
MISSIONGAMEPLAY=bmost
MISSION_CAT3=mrwht

[bmyap]
SanFierro=bmyap,wmycon
MISSIONGAMEPLAY=bmyap
MISSIONALL=bmyap
MISSION_DECON=wmycon

[bmybe]
MARKST=bmybe,mexcab
MISSIONALL=bmybe
MISSIONGAMEPLAY=bmybe
MISSION_SCRASH2=mexcab

[wbdyg1]
EASB2=wbdyg1,wmypig,bmypig
MISSIONALL=wbdyg1
MISSIONGAMEPLAY=wbdyg1
MISSION_STEAL4=wmypig,bmypig

[bmydrug]
LACRAK=balman

[dwmolc1]
ELCA1=dwmolc1,dnmolc1
ELCA2=dwmolc1,dnmolc1
MISSIONALL=dwmolc1
MISSIONGAMEPLAY=dwmolc1
MISSION_CASINO4=dnmolc1

[dwmolc2]
ELCA1=dwmolc2,wmytx1
ELCA2=dwmolc2,wmytx1
MISSIONALL=dwmolc2
MISSIONGAMEPLAY=dwmolc2
MISSION_CASINO4=wmytx1

[dwmylc1]
ELCA1=dwmylc1,wmytx2
ELCA2=dwmylc1,wmytx2
MISSIONALL=dwmylc1
MISSIONGAMEPLAY=dwmylc1
MISSION_CASINO4=wmytx2

[hfyri]
DOH2=hfyri,hfydriv
MISSIONALL=hfyri
MISSIONGAMEPLAY=hfyri
MISSION_STEAL5=hfydriv

[hmyri]
SMB2=hmyri,jrnalst
SMB1=hmyri,jrnalst
ROD3A=hmyri,jrnalst
ROD3B=hmyri,jrnalst
ROD1A=hmyri,jrnalst
MISSIONALL=hmyri
MISSIONGAMEPLAY=hmyri
MISSION_SCRASH2=jrnalst

[hmycr]
SanFierro=sbmycr

[omokung]
SANB1=omokung,snake
MISSIONALL=omokung
MISSIONGAMEPLAY=omokung
MISSION_WUZI5=snake

[wmymech]
SanFierro=wmymech,trimech
LasVenturas=wmymech,wmycon,trimech
MISSIONALL=wmymech
MISSIONGAMEPLAY=wmymech
MISSION_SYN7=trimech
MISSION_DOC2=wmycon
MISSION_HEIST4=trimech

[wmycr]
SanFierro=swmycr

[wmyst]
PANOP=wmyst,claude
MISSIONGAMEPLAY=wmyst
MISSIONALL=wmyst
MISSION_CPRACE=claude

[lsv2]
ELS2=lsv2,freddy
MISSIONALL=lsv2
MISSIONGAMEPLAY=lsv2
MISSION_TWAR7=freddy

[maffa]
SanFierro=maffa,bft1
LasVenturas=maffa,vmaff1
MISSIONALL=maffa
MISSIONGAMEPLAY=maffa
MISSION_HEIST3=vmaff1
MISSION_WUZI1=bft1

[maffb]
SanFierro=maffb,bft2
MISSIONALL=maffb
MISSIONGAMEPLAY=maffb
MISSION_WUZI1=bft2

[mafboss]
SanFierro=mafboss,mediatr
MISSIONALL=mafboss
MISSIONGAMEPLAY=mafboss
MISSION_WUZI1=mediatr

[wmybu]
MTCHI1=wmybu,carver
DOH2=wmybu,reporter
MARKST=wmybu,reporter
MISSIONALL=wmybu
MISSIONGAMEPLAY=wmybu
MISSION_BCRASH1=carver
MISSION_SCRASH2=reporter

[cwmyhb1]
LasVenturas=cwmyhb1,benny
MISSIONALL=cwmyhb1
MISSIONGAMEPLAY=cwmyhb1
MISSION_HEIST3=benny

[vwfywai]
PDOMES=wfywai,bfywai
PDOMES2=wfywai,bfywai
BATTP=wfywai,bfywai
MergeInteriorsWithCitiesAndZones=1

[swmyri]
FINA=swmyri,da
MISSIONGAMEPLAY=swmyri
MISSIONALL=swmyri
MISSION_SCRASH3=da

[laemt1]
LasVenturas=lvemt1

[290]
Global=290,sweet3,smoke3,ogburg,sweet5,sweet6,cesar4,cesar3,truth2,maccerd,sindac2,maddog2
BLUF2,ELCO1=290,cesar3
RED=290
PANOP=wmyst
MISSIONGAMEPLAY=290
MISSIONALL=290
MISSION_SWEET1=sweet3
MISSION_TWAR7=smoke3
MISSION_SMOKE2=smoke3
MISSION_SMOKE3=smoke3
MISSION_DRUGS1=smoke3
MISSION_MUSIC2=ogburg
MISSION_MUSIC5=sweet5
MISSION_CESAR1=cesar3
MISSION_CPRACE=cesar3
MISSION_DRUGS4=sweet6
MISSION_SYN1=cesar4
MISSION_SYN5=cesar4
MISSION_STEAL2=cesar3
MISSION_STEAL4=cesar3
MISSION_TORENO2=cesar4
MISSION_MAF4=truth2
MISSION_CASINO4=maccerd
MISSION_CASINO5=sindac2
MISSION_DOC2=maddog2

[291]
Global=291,ryder4,sweet5,smoke4,cat2,ryder5,pauld,sindac3
MISSIONGAMEPLAY=291
MISSIONALL=291
MISSION_SWEET4=ryder4
MISSION_TWAR7=sweet5
MISSION_MUSIC5=ryder4
MISSION_DRUGS4=smoke4
MISSION_CPRACE=cat2
MISSION_SYN1=ryder5
MISSION_SYN5=ryder5
MISSION_CASINO4=pauld
MISSION_CASINO6=sindac3

[292]
Global=292,sweet2,ryder4
MISSIONGAMEPLAY=292
MISSIONALL=292
MISSION_SWEET4=sweet2
MISSION_DRUGS4=ryder4

[293]
Global=293,dwayne2
MISSIONGAMEPLAY=293
MISSIONALL=293
MISSION_GARAG1=dwayne2

[299]
Global=299,smoke2,smoke5
MISSIONGAMEPLAY=299
MISSIONALL=299
MISSION_SWEET1=smoke2
MISSION_SWEET4=smoke5

;Restored on traffic

[wmycon]
Global=wmycon,bmycon

;New Special Characters

[BALMAN]
Voice=ballas2

[SLUT]
Voice=wfysex
AnimGroup=woman

[sweet,sweet2,sweet3,sweet4,sweet5,sweet6,swtshot]
AnimGroup=gang2
UseParentVoice=1

[smoke,smoke2,smoke3,smoke4,smoke5]
AnimGroup=fatman
UseParentVoice=1

[ryder,ryder2,ryder3,ryder4]
AnimGroup=gang1
UseParentVoice=1

[ryder5]
AnimGroup=gang1
UseParentVoice=1

[cesar,cesar3,cesar4]
UseParentVoice=1

[freddy]
UseParentVoice=1

[grass]
Voice=ballas3

[kane]
UseParentVoice=1

[ogloc,ogburg]
UseParentVoice=1
AnimGroup=man

[alan]
UseParentVoice=1

[carver]
Voice=heck1

[mrwht]
Voice=heck1

[claude2]
UseParentVoice=1

[cat,cat2]
AnimGroup=woman
UseParentVoice=1

[dwayne2]
UseParentVoice=1

[da]
UseParentVoice=1

[balgrd]
UseParentVoice=1

[reporter]
UseParentVoice=1

[jrnalst]
UseParentVoice=1

[mexcab]
Voice=vhmycr

[snake]
UseParentVoice=1

[trimech]
Voice=triada

[bogman]
Voice=heck1

[bettina]
Voice=wfysex

[dancea,danceb,hornd]
Voice=wfysex

[bfywai,wfywai]
UseParentVoice=1

[faketor]
Voice=heck1

[bmypig]
Voice=wbdyg1
AnimGroup=man

[wmypig]
Voice=wmysgrd
AnimGroup=man

[hfydriv]
UseParentVoice=1

[truth2]
UseParentVoice=1

[wmytx1]
UseParentVoice=1

[wmytx2]
UseParentVoice=1

[pauld]
UseParentVoice=1

[maccerd]
UseParentVoice=1

[benny]
Voice=wmoice
AnimGroup=fatman

; DLC


;Ballas

[ballas1]
Global=ballas1,ballas4
JEF3A,JEF3C,JEF2,JEF1B,JEF1A,JEF3B,ELS1A,ELS1B,ELS2,LIND3,LIND2A,LIND2B,CHC2B,CHC3,LDOC1B,LDOC1A=rhb1
GLN1,GLN2A,LIND1A,LIND1B=ktb1
SUN1,SUN2,SUN3A,SUN3B,SUN3C,SUN4=tdb1
GAN1=ballas1,ballas2,ballas3,ballas4,ballas5,rhb1,rhb2,rhb3,ktb1,ktb2,ktb3,tdb1,tdb2,tdb3
MKT1=ktb1,ktb2,ktb3
MULINT,LDT4,LDT6,LDT1B,LDT1C,GLN1B=ballas1,ballas2,ballas3,ballas4,ballas5,rhb1,rhb2,rhb3,ktb1,ktb2,ktb3,tdb1,tdb2,tdb3
ANGPI=balgrd
SanFierro=ballas1,ballas2,ballas3
LACRAK=ballas1,ballas2,ballas3
MISSIONALL=ballas1,ballas4
MISSIONGAMEPLAY=ballas1,ballas4
MISSION_SWEET1B=ballas1,ballas2,ballas3
MISSION_SWEET7=rhb2
MISSION_LA1FIN2=ballas1,ballas2,ballas3,ballas4,ballas5,rhb1,rhb2,rhb3,ktb1,ktb2,ktb3,tdb1,tdb2,tdb3
MISSION_SYN1=balgrd
MISSION_SYN5=ballas1,ballas2,ballas3

[ballas2]
JEF3A,JEF3C,JEF2,JEF1B,JEF1A,JEF3B,ELS1A,ELS1B,ELS2,LIND3,LIND2A,LIND2B,CHC2B,CHC3,LDOC1B,LDOC1A=rhb2,ktb2
GLN1,GLN2A,LIND1A,LIND1B=ktb2
SUN1,SUN2,SUN3A,SUN3B,SUN3C,SUN4=tdb2
GAN1=ballas1,ballas2,ballas3,ballas4,ballas5,rhb1,rhb3,ktb1,ktb2,ktb3,tdb1,tdb2,tdb3
MKT1=ktb1,ktb2,ktb3
SanFierro=ballas1,ballas2,ballas3
MISSIONALL=rhb2,ballas2
MISSIONGAMEPLAY=rhb2,ballas2
MISSION_SWEET3=ktb2
MISSION_MUSIC5=ballas1,ballas2,ballas3,rhb1,rhb3,ktb1,ktb2,ktb3,tdb1,tdb2,tdb3
MISSION_SWEET7=rhb1,rhb3
MISSION_SYN5=ballas1,ballas2,ballas3

[rhb2]
Global=rhb2,ktb2
MISSIONALL=rhb2
MISSIONGAMEPLAY=rhb2
MISSION_SWEET3=ktb2

[ballas3]
Global=ballas3,ballas5
JEF3A,JEF3C,JEF2,JEF1B,JEF1A,JEF3B,ELS1A,ELS1B,ELS2,LIND3,LIND2A,LIND2B,CHC2B,CHC3,LDOC1B,LDOC1A=rhb3
GLN1,GLN2A,LIND1A,LIND1B=ktb3
SUN1,SUN2,SUN3A,SUN3B,SUN3C,SUN4=tdb3
GAN1=ballas1,ballas2,ballas3,ballas4,ballas5,rhb1,rhb3,ktb1,ktb2,ktb3,tdb1,tdb2,tdb3
MKT1=ktb1,ktb2,ktb3
VIN2=kane
MISSIONALL=ballas3,ballas5
MISSIONGAMEPLAY=ballas3,ballas5
MISSION_MUSIC5=ballas1,ballas2,ballas3,ballas4,ballas5,rhb1,rhb2,rhb3,ktb1,ktb2,ktb3,tdb1,tdb2,tdb3
MISSION_SWEET7=kane

;Families

[fam1]
GAN1,GAN2=fam1,fam4
PLS,LIND4A,LIND4C=sev1,sev3
SUN1,SUN2,SUN3A,SUN3B,SUN3C,SUN4=tem1
JEF1A,ELS1A,CHC2B,MOTEL=fam1,fam4,fam5,sev2
MULINT,LDT4,LDT6,LDT1B,LDT1C,GLN1B=fam1,fam2,fam3,fam4,fam5
MISSIONGAMEPLAY=fam1,sev1,tem1
MISSIONALL=fam1,sev1,tem1
MISSION_HOODS5=sev1,sev3
MISSION_SWEET7=fam1,fam4
MISSION_DRUGS4=fam4,fam5,sev2
MISSION_LA1FIN2=fam1,fam2,fam3,fam4,fam5

[fam2]
GAN1,GAN2=fam2,fam3,fam5
PLS,LIND4A,LIND4C=sev2
SUN1,SUN2,SUN3A,SUN3B,SUN3C,SUN4=tem2
JEF1A,ELS1A,CHC2B,MOTEL=fam2,sev3,tem1,tem3
MISSIONGAMEPLAY=fam2,sev2,tem2
MISSIONALL=fam2,sev2,tem2
MISSION_SWEET7=fam2,fam3,fam5
MISSION_DRUGS4=sev3,tem1,tem3
MISSION_LA1FIN2=fam1,fam2,fam3

[fam3]
Global=fam3,fam4,fam5
GAN1,GAN2=fam3,fam4,fam5,fam1,fam2
PLS,LIND4A,LIND4C=sev3
SUN1,SUN2,SUN3A,SUN3B,SUN3C,SUN4=tem3
JEF1A,ELS1A,CHC2B,MOTEL=fam3,sev1,tem2
MISSIONGAMEPLAY=fam3,fam4,fam5,sev3,tem3
MISSION_MUSIC5=fam1,fam2
MISSION_DRUGS4=sev1,tem2
MISSION_LA1FIN2=fam1,fam2,fam3

;Vagos
[lsv1]
Global=lsv1,lsv4
MISSIONGAMEPLAY=lsv1,lsv4
MISSIONALL=lsv1,lsv4
MISSION_SMOKE2=lsv1

[lsv3]
Global=lsv3,lsv5

;Aztecas
[vla1]
Global=vla1,vla4

[vla2]
Global=vla2,vla5

;San Fierro Rifa
[sfr1]
Global=sfr1,sfr2,sfr3,sfr4,sfr5
MISSIONGAMEPLAY=sfr1
MISSIONALL=sfr1
MISSION_SYN5=sfr1,sfr2,sfr3,sfr4,sfr5

[sfr2]
Global=sfr2,sfr4
SanFierro=sfr1,sfr2,sfr3,sfr4,sfr5
MISSIONGAMEPLAY=sfr2,sfr4
MISSIONALL=sfr2,sfr4
MISSION_SYN5=sfr1,sfr2,sfr3,sfr4,sfr5

[sfr3]
Global=sfr3,sfr5

;Da Nang Boys
[dnb1]
Global=dnb1,dnb5
SANB1=dnb1,dnb2,dnb5

[dnb2]
Global=dnb2,dnb4

;Triads
[triada]
Global=triada,triade
SanFierro=triada,triade,triadb,triadc,triadd
MISSIONGAMEPLAY=triada,triade
MISSIONALL=triada,triade
MISSION_SYN5=triada,triade,triadb,triadc,triadd
MISSION_HEIST4=triada

[triadb]
Global=triadb,triadc

[triboss]
Global=triboss,triadd
MISSIONGAMEPLAY=triboss,triadd
MISSIONALL=triboss,triadd
MISSION_SYN5=triboss

[wmyboun]
TRICAS=triada,triadb

[bmyboun]
TRICAS=triada,triadb

;Vegas Mafia
[vmaff1]
Global=vmaff1,sind1,fora,forb
CALI1,CALI2,MAFCAS=vmaff1
ABATOIR=sind1
MISSIONGAMEPLAY=vmaff1
MISSIONALL=vmaff1
MISSION_CASINO3=sind1
MISSION_CASINO5=fora,forb
MISSION_CASINO6=sind1
MISSION_CASINO9=fora

[vmaff2]
Global=vmaff2,sind2,forb,forc,ford,fore
CALI1,CALI2,MAFCAS=vmaff2
ABATOIR=sind2
JETINT=forb
MISSIONGAMEPLAY=vmaff2
MISSIONALL=vmaff2
MISSION_CASINO3=sind2
MISSION_CASINO5=forc,ford,fore
MISSION_CASINO6=sind2
MISSION_CASINO9=forb

[vmaff3]
Global=vmaff3,forema,forc
CALI1,CALI2,MAFCAS=vmaff3
WWE=vmaff3,sind3
ABATOIR=sind4,sind5
MISSIONGAMEPLAY=vmaff3
MISSIONALL=vmaff3
MISSION_CASINO3=sind3
MISSION_CASINO5=sind3,forema
MISSION_CASINO6=sind4,sind5
MISSION_CASINO9=forc

[vmaff4]
Global=vmaff4,vmaff5,foremb,ford,fore
CALI1,CALI2,MAFCAS=vmaff4,vmaff5
WWE=vmaff4,sind4,sind5
ABATOIR=sind3
MISSIONGAMEPLAY=vmaff4,vmaff5
MISSIONALL=vmaff4,vmaff5
MISSION_CASINO3=sind4,sind5
MISSION_CASINO5=sind4,sind5,foremb
MISSION_CASINO6=sind3
MISSION_CASINO9=ford,fore

[ballas4,ballas5]
UseParentVoice=1

[rhb1,rhb2,rhb3]
UseParentVoice=1

[ktb1,ktb2,ktb3]
UseParentVoice=1

[tdb1]
Voice=ballas2
AnimGroup=fatman

[tdb2]
Voice=ballas1

[tdb3]
UseParentVoice=1

[fam4,fam5]
UseParentVoice=1

[sev1,sev2,sev3]
UseParentVoice=1

[tem1,tem2,tem3]
UseParentVoice=1

[lsv4,lsv5]
UseParentVoice=1

[vla4,vla5]
UseParentVoice=1

[dnb4,dnb5]
UseParentVoice=1

[sfr4,sfr5]
UseParentVoice=1

[triadc,triadd,triade]
UseParentVoice=1

[vmaff5]
Voice=vmaff1

[sind1]
Voice=vmaff1

[sind2]
Voice=vmaff4

[sind3]
Voice=vmaff3

[sind4]
Voice=vmaff2
AnimGroup=fatman

[sind5]
Voice=vmaff2

[fora]
Voice=vmaff2
AnimGroup=fatman

[forb]
Voice=vmaff3

[forc]
Voice=vmaff1

[ford]
Voice=vmaff4
AnimGroup=fatman

[fore]
Voice =vmaff3

;Cops

[lapd1]
POLICE1=lapd1,detla1,detla2
LosSantos=lapd1,lapdv1
Wanted1=lapd1
Wanted2=lapd1
Wanted3=lapdv1
Wanted4=lapdv1
Wanted5=lapdv1
Wanted6=lapdv1

[sfpd1]
POLICE2=sfpd1,detsf1,detsf2
SanFierro=sfpd1,sfpdv1
Wanted1=sfpd1
Wanted2=sfpd1
Wanted3=sfpdv1
Wanted4=sfpdv1
Wanted5=sfpdv1
Wanted6=sfpdv1

[lvpd1]
POLICE3=lvpd1,detlv1,detlv2
LasVenturas=lvpd1,lvpdv1
Wanted1=lvpd1
Wanted2=lvpd1
Wanted3=lvpdv1
Wanted4=lvpdv1
Wanted5=lvpdv1
Wanted6=lvpdv1

[csher]
Countryside=csher,csherv
LEAFY=csher,csherh1
Wanted1=csher,csherh1
Wanted2=csher,csherh1
Wanted3=csherv
Wanted4=csherv
Wanted5=csherv
Wanted6=csherv
Desert=dsher
MISSIONALL=csher,csherv,dsher
MISSIONGAMEPLAY=csher,csherv,dsher
MISSION_TRUTH2=csherh1

[lapdm1]
SanFierro=sfpdm1
LasVenturas=lvpdm1
Desert=dsherm1
Countryside=csherm1

[swat]
LosSantos=swatla1,swatla2
SanFierro=swatsf1,swatsf2
LasVenturas=swatlv1,swatlv2
Countryside=swatc1,swatc2
Desert=swatd1,swatd2

[fbi]
Global=fbi,fbi2,fbi3,fbi4,fbi5

[army]
Global=army,army1,army2,army3

[dsher]
Desert=dsher,dsherv
Wanted1=dsher
Wanted2=dsher
Wanted3=dsherv
Wanted4=dsherv
Wanted5=dsherv
Wanted6=dsherv

[lapdv1,sfpdv1,lvpdv1,lapdr1,lapdrv1]
UseParentVoice=1

[sfpdm1,lvpdm1,dsherm1,csherm1]
UseParentVoice=1

[detla1,detla2]
Voice=heck1

[detsf1,detsf2]
Voice=heck1

[detlv1,detlv2]
Voice=heck1

[swatc1,swatc2,swatd1,swatd2,swatla1,swatla2,swatsf1,swatsf2,swatlv1,swatlv2]
UseParentVoice=1

[swatr1,swatr2]
Voice=swat

[fbi2,fbi3,fbi4,fbi5]
UseParentVoice=1

[army1,army2,army3]
UseParentVoice=1

[csherv,dsherv]
UseParentVoice=1

[csherh1]
LosSantos=lapdh1
SanFierro=sfpdh1
LasVenturas=lvpdh1
Desert=dsherh1
Voice=csher

[lapdh1]
Voice=lapd1

[sfpdh1]
Voice=sfpd1

[lvpdh1]
Voice=lvpd1

[dsherh1]
Voice=dsher

[sanews]
Voice=wmysgrd