[Settings]
EnablePeds=1
EnableSpecialPeds=1
EnableVehicles=1
EnablePedWeapons=1
EnableStreamingFix=1
LowMemoryProtection=3300
#CONTROLS
DisableKey=115
ReloadKey=117
DebugKey=119
#DEBUGGING
EnableLog=0
EnableNullGuards=0
LogJumps=0
ForceEnable=0
LoadStage=0
TrackReferenceCounts=-1
DebugDrawSize=0.28
DebugDrawX=20.0
DebugDrawY=340.0
DebugDrawPeds=0xC3
DebugDrawVehicles=0x43
[Limits]
ExtraObjectsDirLimit=4000
MaxModelID=20000
StreamingMemory=
[Areas]
Countryside=RED,WHET,FLINTC
LosSantos=LA
SanFierro=SF
LasVenturas=VE
Desert=ROBAD,ROBAD1,BONE
TierraRobada=ROBAD,ROBAD1
BoneCounty=BONE
RedCounty=RED
Blueberry=BLUEB,BLUEB1
Montgomery=MONT,MONT1
Dillimore=DILLI
PalominoCreek=PALO
FlintCounty=FLINTC
Whetstone=WHET
AngelPine=ANGPI