[Settings]
ChangeCarGenerators=0
ChangeScriptedCars=1
DisablePayAndSpray=1
EnableLights=1
EnableTrailerBrakeLights=1
EnableSideMissions=1
EnableSiren=1
EnableSpecialFeatures=0
ExcludeCarGeneratorModels=492,600
ExcludeModelsFromInheritance=596,597,598,599,490,497,472,432,433

;Missions 

[sentinel]
Global=sentinel,sentxs
EASB2=sentinel,secucar
LasVenturas =
CAL1 = sentxs
CAL2 = sentxs
PLS=sentinel,greenwoo
LDT4,LDT6,LDT1B,LDT1C,GLN1B=sentinel,sentxs,greenwoo
MULINT=sentinel,sentxs,tahoma
MISSIONALL=sentinel,sentxs
MISSIONGAMEPLAY=sentinel,sentxs
MISSION_HOODS5=greenwoo
MISSION_LA1FIN2=greenwoo,tahoma
MISSION_STEAL4=secucar

[stretch]
SFAIR1=stretch,washing
MISSIONGAMEPLAY=stretch
MISSIONALL=stretch
MISSION_DRIV3=washing

[securica]
QUARY=securica,secucar
MISSIONGAMEPLAY=securica
MISSIONALL=securica
MISSION_CASINO2=secucar

[banshee]
Global=banshee,sultan
MISSIONGAMEPLAY=banshee
MISSIONALL=banshee
MISSION_SYN5=sultan

[rancher]
CHINA=rancher,rnchlure
MISSIONGAMEPLAY=rancher
MISSIONALL=rancher
MISSION_DRIV6=rnchlure

[greenwoo]
GAN1=greenwoo,Impaler
MISSIONGAMEPLAY=greenwoo
MISSIONALL=greenwoo
MISSION_SWEET4=Impaler

; DLC


;Impaler

[Impaler]
ParentModel=

;Police Bikes

[copcarru]
Global=copcarru,copbikru
Wanted1=copcarru,copbikru
Wanted2=copcarru,copbikru
Wanted3=copcarru,copbikru
Wanted4=copcarru
Wanted5=copcarru
Wanted6=copcarru

[copbike]
LosSantos=copbikls
SanFierro=copbiksf
LasVenturas=copbikvg
Countryside=copbikru
Desert=copbikru

[copbikls,copbiksf,copbikvg,copbikru]
ParentModel=copbike

;Police Mavericks

[polmav]
Drivers=csherh1,lapdh1,sfpdh1,lvpdh1,dsherh1
Passengers=csherh1,lapdh1,sfpdh1,lvpdh1,dsherh1
ReplaceDriver=1
ReplacePassengers=1
LosSantos=polmavls
SanFierro=polmavsf
LasVenturas=polmavvg

[polmavls,polmavsf,polmavvg]
ParentModel=polmav

; FBI Rancher | FBI Truck
[fbiranch]
LosSantos=fbiranch,fbitruck
CountrySide=fbiranch,fbitruck
SanFierro=fbiranch,fbitruck
Desert=fbiranch,fbitruck
LasVenturas=fbiranch,fbitruck
MISSIONALL=fbiranch,fbiranch
MISSIONGAMEPLAY=fbiranch,fbiranch
MISSION_VCRASH1=fbiranch

[fbitruck]
LightSize=0.0
LightWidth=0.0
LightZ=-0.2
LightY=0.3
LightR=0
LightG=0
LightB=0
LightA=0
LightR2=0
LightG2=0
LightB2=0
LightA2=0

; Enforcer | SWAT APC
[enforcer]
LosSantos=enforcls,swatvan
SanFierro=enforcsf,swatvan
LasVenturas=enforcvg,swatvan
CountrySide=enforcer,swatvan
Desert=enforcer,swatvan

[swatvan]
LightSize=0.0
LightWidth=0.0
LightZ=-0.2
LightY=0.3
LightR=0
LightG=0
LightB=0
LightA=0
LightR2=0
LightG2=0
LightB2=0
LightA2=0

[enforcls,enforcsf,enforcvg]
ParentModel=enforcer

;Unmarked Police
[copcarla]
LosSantos=copcarla,detcar
Wanted1=copcarla
Wanted2=copcarla
Wanted3=copcarla,detcar
Wanted4=copcarla,detcar
Wanted5=copcarla,detcar
Wanted6=copcarla,detcar
MISSIONALL=copcarla,detcar
MISSIONGAMEPLAY=copcarla,detcar
MISSION_LA1FIN2=copcarla

[copcarsf]
SanFierro=copcarsf,detcar
Wanted1=copcarsf
Wanted2=copcarsf
Wanted3=copcarsf,detcar
Wanted4=copcarsf,detcar
Wanted5=copcarsf,detcar
Wanted6=copcarsf,detcar

[copcarvg]
LasVenturas=copcarvg,detcarvg
Wanted1=copcarvg
Wanted2=copcarvg
Wanted3=copcarvg,detcarvg
Wanted4=copcarvg,detcarvg
Wanted5=copcarvg,detcarvg
Wanted6=copcarvg,detcarvg

[detcar]
DriverGroup1=detla1,detla2
PassengerGroup1=detla1,detla2
DriverGroup2=detsf1,detsf2
PassengerGroup2=detsf1,detsf2
LosSantos=OccupantGroup1
SanFierro=OccupantGroup2
UseOnlyGroups=1
LightWidth=0.0
LightX=0.02
LightZ=-0.7
LightY=1.2
LightR=255
LightG=0
LightB=0
LightA=40
LightR2=255
LightG2=0
LightB2=0
LightA2=40
ParentModel=copcarla

[detcarvg]
DriverGroup1=detlv1,detlv2
PassengerGroup1=detlv1,detlv2
LasVenturas=OccupantGroup1
UseOnlyGroups=1
LightWidth=0.0
LightX=0.02
LightZ=-0.6
LightY=1.1
LightR=255
LightG=0
LightB=0
LightA=40
LightR2=255
LightG2=0
LightB2=0
LightA2=40
ParentModel=copcarvg

;Army
[barracks]
Global=barracks,patriot
Wanted1=barracks
Wanted2=barracks
Wanted3=barracks
Wanted4=barracks
Wanted5=barracks
Wanted6=barracks,patriot

[patriot]
LightSize=0.0
LightWidth=0.0
LightZ=-0.2
LightY=0.3
LightR=0
LightG=0
LightB=0
LightA=0
LightR2=0
LightG2=0
LightB2=0
LightA2=0

;Sannews
[vcnmav]
Drivers=sanews
Passengers=sanews
ReplaceDriver=1
ReplacePassengers=1
