[Settings]
ChangeCarGenerators=0
ChangeScriptedCars=1
DisablePayAndSpray=1
EnableLights=1
EnableTrailerBrakeLights=1
EnableSideMissions=1
EnableSiren=1
EnableSpecialFeatures=0
ExcludeCarGeneratorModels=492,600
ExcludeModelsFromInheritance=596,597,598,599,490,497,472,432,433

;Missions 

[405]
Global= 405, sentxs
EASB2=
LasVenturas =
CAL1 = sentxs
CAL2 = sentxs

[409]
Global=

[428]
QUARY=

[429]
Global=

[489]
Global=

[492]
Global=
ParentModel=

; DLC


;Impaler

[14000]
ParentModel=

;Police Bikes

[599]
Global=599,14004
Wanted1=599,14004
Wanted2=599,14004
Wanted3=599,14004
Wanted4=599
Wanted5=599
Wanted6=599

[523]
LosSantos=14001
SanFierro=14002
LasVenturas=14003
Countryside=14004
Desert=14004

[14001,14002,14003,14004]
ParentModel=523

;Police Mavericks

[497]
Drivers=csherh1,lapdh1,sfpdh1,lvpdh1,dsherh1
Passengers=csherh1,lapdh1,sfpdh1,lvpdh1,dsherh1
ReplaceDriver=1
ReplacePassengers=1
LosSantos=14005
SanFierro=14006
LasVenturas=14007

[14005,14006,14007]
ParentModel=497

; FBI Rancher | FBI Truck
[490]
LosSantos=490,528
CountrySide=490,528
SanFierro=490,528
Desert=490,528
LasVenturas=490,528

[528]
LightSize=0.0
LightWidth=0.0
LightZ=-0.2
LightY=0.3
LightR=0
LightG=0
LightB=0
LightA=0
LightR2=0
LightG2=0
LightB2=0
LightA2=0

; Enforcer | SWAT APC
[427]
Global=427,601
LosSantos=14008,601
SanFierro=14009,601
LasVenturas=14010,601

[601]
LightSize=0.0
LightWidth=0.0
LightZ=-0.2
LightY=0.3
LightR=0
LightG=0
LightB=0
LightA=0
LightR2=0
LightG2=0
LightB2=0
LightA2=0

[14008,14009,14010]
ParentModel=427

;Unmarked Police
[596]
LosSantos=596,14011
Wanted1=596
Wanted2=596
Wanted3=596,14011
Wanted4=596,14011
Wanted5=596,14011
Wanted6=596,14011
DisableOnMission=

[597]
SanFierro=597,14011
Wanted1=597
Wanted2=597
Wanted3=597,14011
Wanted4=597,14011
Wanted5=597,14011
Wanted6=597,14011

[598]
LasVenturas=598,14012
Wanted1=598
Wanted2=598
Wanted3=598,14012
Wanted4=598,14012
Wanted5=598,14012
Wanted6=598,14012

[14011]
DriverGroup1=detla1,detla2
PassengerGroup1=detla1,detla2
DriverGroup2=detsf1,detsf2
PassengerGroup2=detsf1,detsf2
LosSantos=OccupantGroup1
SanFierro=OccupantGroup2
UseOnlyGroups=1
LightWidth=0.0
LightX=0.02
LightZ=-0.7
LightY=1.2
LightR=255
LightG=0
LightB=0
LightA=40
LightR2=255
LightG2=0
LightB2=0
LightA2=40
ParentModel=596

[14012]
DriverGroup1=detlv1,detlv2
PassengerGroup1=detlv1,detlv2
LasVenturas=OccupantGroup1
UseOnlyGroups=1
LightWidth=0.0
LightX=0.02
LightZ=-0.6
LightY=1.1
LightR=255
LightG=0
LightB=0
LightA=40
LightR2=255
LightG2=0
LightB2=0
LightA2=40
ParentModel=598

;Army
[433]
Global=433,470
Wanted1=433
Wanted2=433
Wanted3=433
Wanted4=433
Wanted5=433
Wanted6=433,470

[470]
LightSize=0.0
LightWidth=0.0
LightZ=-0.2
LightY=0.3
LightR=0
LightG=0
LightB=0
LightA=0
LightR2=0
LightG2=0
LightB2=0
LightA2=0

[528]
LightSize=0.0
LightWidth=0.0
LightZ=-0.2
LightY=0.3
LightR=0
LightG=0
LightB=0
LightA=0
LightR2=0
LightG2=0
LightB2=0
LightA2=0

;Sannews
[488]
Drivers=sanews
Passengers=sanews
ReplaceDriver=1
ReplacePassengers=1
