name: Upload Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Vanilla Assets
        uses: i3h/download-release-asset@v1
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          tag: data
          file: sa_cuts.7z
          path: .resources/.sa
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Vanilla Assets
        shell: cmd
        run: |
          cd .resources/.sa
          7z x sa_cuts.7z -aoa -o../../
          cd ../..

      - name: Build All
        shell: cmd
        run: build_all.bat

      - name: Pack All
        uses: ThirteenAG/zip-release@master
        with:
          path: ./*
          type: 'zip'
          filename: 'SACCF.7z'
          exclusions: '.git .github .resources .ipls .cdimages build_all.bat readme.md'
          
      - name: Pack Extras
        uses: ThirteenAG/zip-release@master
        with:
          path: ./*
          type: 'zip'
          filename: 'SACCF-Extras.7z'
          exclusions: '.git .github .resources .ipls models modloader scripts .cdimages build_all.bat readme.md'

      - name: Get Release Info
        id: release_info
        uses: cardinalby/git-get-release-action@1.2.4
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: latest

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          name: ${{ steps.release_info.outputs.name }}
          body: ${{ steps.release_info.outputs.body }}
          tag: ${{ steps.release_info.outputs.tag_name }}
          artifacts: SACCF.7z, SACCF-Extras.7z
